// Blog post bank for social media carousels.
// Each entry maps to a blog post on olympiadready.com/blog/<slug>.
// slides: 3–4 items, each with an emoji icon + one punchy line.
// audience: "parents" | "students" | "schools" — shapes caption angle.

module.exports = [
  {
    id: "blog-01",
    slug: "imo-preparation-class-1",
    title: "IMO Prep for Class 1",
    hook: "Your Class 1 child's first Olympiad doesn't have to be stressful.",
    tag: "Maths · Class 1",
    color: "#2563EB",
    audience: "parents",
    slides: [
      { icon: "📝", text: "35 questions · 60 minutes · No negative marking" },
      { icon: "🔢", text: "Focus: counting, addition, shapes, patterns & logical reasoning" },
      { icon: "⏱️", text: "10 minutes a day beats 1 hour on weekends — always" },
      { icon: "🎯", text: "Achievers section = last 5 questions · hardest · highest marks" },
    ],
  },
  {
    id: "blog-02",
    slug: "imo-preparation-class-2",
    title: "IMO Prep for Class 2",
    hook: "Class 2 IMO is manageable. Here's the exact syllabus & plan.",
    tag: "Maths · Class 2",
    color: "#2563EB",
    audience: "parents",
    slides: [
      { icon: "📊", text: "3 sections: Logical Reasoning · Maths · Achievers (3 marks each)" },
      { icon: "✖️", text: "Know tables 2–5 cold — slow recall causes errors under time pressure" },
      { icon: "📅", text: "6-week plan: 10–15 min/day on school days, 25 min weekends" },
      { icon: "🏆", text: "Achievers section = 15 of 40 marks · don't skip it" },
    ],
  },
  {
    id: "blog-03",
    slug: "imo-preparation-class-3",
    title: "IMO Prep for Class 3",
    hook: "Class 3 is when IMO gets real — Level 2 qualification starts here.",
    tag: "Maths · Class 3",
    color: "#2563EB",
    audience: "parents",
    slides: [
      { icon: "⚡", text: "From Class 3, top scorers qualify for Level 2 national round" },
      { icon: "⌚", text: "Tricky topic: elapsed time — 'journey from 10:15 to 12:40 pm?'" },
      { icon: "🧩", text: "Logical reasoning = 10 questions · often the easiest marks on paper" },
      { icon: "📐", text: "Perimeter with a missing side & fractions in context — practise these" },
    ],
  },
  {
    id: "blog-04",
    slug: "imo-preparation-class-5",
    title: "IMO Prep for Class 5",
    hook: "The Achievers section decides your child's rank in Class 5 IMO.",
    tag: "Maths · Class 5",
    color: "#2563EB",
    audience: "parents",
    slides: [
      { icon: "🎯", text: "Achievers = 5 questions × 3 marks = 15 marks — the rank decider" },
      { icon: "🔢", text: "Highest-weight topics: LCM/HCF, fractions, geometry" },
      { icon: "🚫", text: "Most common mistake: skipping logical reasoning in prep" },
      { icon: "🕐", text: "Never done a timed mock? That's the single biggest risk on exam day" },
    ],
  },
  {
    id: "blog-05",
    slug: "imo-preparation-class-6",
    title: "IMO Prep for Class 6",
    hook: "Class 6 IMO jumps to 50 questions. Time management is now critical.",
    tag: "Maths · Class 6",
    color: "#2563EB",
    audience: "students",
    slides: [
      { icon: "📈", text: "50 questions · 60 minutes = just 72 seconds per question" },
      { icon: "➕", text: "New topics: integers, basic algebra, ratio & proportion" },
      { icon: "🧠", text: "Most missed: subtracting negatives like −5 − (−3)" },
      { icon: "💡", text: "Skip and return strategy can lift your score by 5–8 marks" },
    ],
  },
  {
    id: "blog-06",
    slug: "imo-preparation-class-8",
    title: "IMO Prep for Class 8",
    hook: "Class 8 IMO is where algebra, compound interest & mensuration combine.",
    tag: "Maths · Class 8",
    color: "#2563EB",
    audience: "students",
    slides: [
      { icon: "📐", text: "New: algebraic identities, factorisation, volumes of 3D shapes" },
      { icon: "💰", text: "Compound interest questions require multi-step reasoning — practise these" },
      { icon: "📅", text: "10-week plan: week 1–2 algebra, week 3–4 mensuration, week 5+ mock exams" },
      { icon: "🏆", text: "Class 8 prep directly strengthens Class 10 board exam foundation" },
    ],
  },
  {
    id: "blog-07",
    slug: "nso-preparation-class-4",
    title: "NSO Prep for Class 4",
    hook: "Class 4 NSO tests why and how — not just what.",
    tag: "Science · Class 4",
    color: "#10b981",
    audience: "parents",
    slides: [
      { icon: "🌱", text: "Top topics: plants, animals, human body — start here" },
      { icon: "🔬", text: "Paper asks why animals adapt, how levers work — not just names" },
      { icon: "🧲", text: "Achievers favourite: simple machines — levers, pulleys, inclined planes" },
      { icon: "📅", text: "6-week plan: science Mon–Thu, logical reasoning Fri, mock in week 6" },
    ],
  },
  {
    id: "blog-08",
    slug: "nso-preparation-class-9",
    title: "NSO Prep for Class 9",
    hook: "Class 9 NSO splits into physics, chemistry & biology for the first time.",
    tag: "Science · Class 9",
    color: "#10b981",
    audience: "students",
    slides: [
      { icon: "⚗️", text: "New structure: Physics · Chemistry · Biology as separate disciplines" },
      { icon: "🚀", text: "Hardest topic: equations of motion combined in one Achievers question" },
      { icon: "🧬", text: "Tissue types (connective subtypes) = frequent exam trap — memorise carefully" },
      { icon: "💡", text: "NSO tracks CBSE closely — board prep IS Olympiad prep, with extra application" },
    ],
  },
  {
    id: "blog-09",
    slug: "olympiad-preparation-class-7",
    title: "Olympiad Prep for Class 7",
    hook: "Class 7 school topics and Olympiad prep overlap more than any earlier year.",
    tag: "Guides · Class 7",
    color: "#8b5cf6",
    audience: "parents",
    slides: [
      { icon: "➕", text: "IMO focus: equations, triangle congruence, percentages & simple interest" },
      { icon: "🔬", text: "NSO covers: acids/bases, motion-time graphs, light & electric circuits" },
      { icon: "📖", text: "IEO: perfect tenses, passive voice, idioms, and reading inference" },
      { icon: "📅", text: "25 min/day · align with school topic · one LR session per week" },
    ],
  },
  {
    id: "blog-10",
    slug: "olympiad-preparation-class-10",
    title: "Olympiads in Class 10 — Do Both",
    hook: "Board exam year ≠ skip Olympiads. Here's why they coexist perfectly.",
    tag: "Guides · Class 10",
    color: "#8b5cf6",
    audience: "parents",
    slides: [
      { icon: "✅", text: "IMO & NSO Class 10 syllabus = same as board exam syllabus" },
      { icon: "🎓", text: "Olympiad rank strengthens profiles for IB and competitive schools" },
      { icon: "🧠", text: "Weak board topic? Olympiad-format practice fixes it faster than re-reading" },
      { icon: "📋", text: "Recommendation: IMO + one science Olympiad · no more in board year" },
    ],
  },
  {
    id: "blog-11",
    slug: "top-10-olympiad-exams",
    title: "Top 10 Olympiads in India",
    hook: "10 Olympiads every Indian school student should know about.",
    tag: "Guides",
    color: "#8b5cf6",
    audience: "parents",
    slides: [
      { icon: "🥇", text: "SOF Olympiads (IMO, NSO, IEO, IGKO) — most widely taken, school-based" },
      { icon: "🔬", text: "NSTSE — tests understanding over memory, great for science stream students" },
      { icon: "📖", text: "Hummingbird Spell Bee — for Class 1–12, builds vocabulary and spelling depth" },
      { icon: "💻", text: "ISSO / NCO — computer science Olympiads, growing fast with coding curriculum" },
    ],
  },
  {
    id: "blog-12",
    slug: "sof-vs-silverzone-vs-crest",
    title: "SOF vs Silverzone vs CREST",
    hook: "Which Olympiad body should your child register with?",
    tag: "Guides",
    color: "#8b5cf6",
    audience: "parents",
    slides: [
      { icon: "🏆", text: "SOF — largest network, school-based, most recognised, IMO/NSO/IEO" },
      { icon: "🥈", text: "Silverzone — strong maths focus, iOM, good for students wanting variety" },
      { icon: "🎓", text: "CREST — adaptive difficulty, strong analytics, good for self-paced prep" },
      { icon: "✅", text: "Most schools register for SOF — check your school's registration first" },
    ],
  },
  {
    id: "blog-13",
    slug: "olympiad-vs-ntse",
    title: "Olympiad vs NTSE — Which to Choose?",
    hook: "Olympiad and NTSE are very different. Here's which fits your child.",
    tag: "Guides",
    color: "#8b5cf6",
    audience: "parents",
    slides: [
      { icon: "📌", text: "NTSE: Class 10 only, scholarship exam, two stages, national ranking" },
      { icon: "🏅", text: "Olympiad: Class 1–12, subject-specific, school-based, international ranking" },
      { icon: "🧠", text: "Overlap: both reward deep understanding over textbook memorisation" },
      { icon: "💡", text: "Recommendation: Olympiads Class 1–9, then add NTSE in Class 10" },
    ],
  },
  {
    id: "blog-14",
    slug: "how-to-prepare-for-nso-in-30-days",
    title: "NSO Prep in 30 Days",
    hook: "30 days to NSO. Here's the only plan you need.",
    tag: "Science",
    color: "#10b981",
    audience: "students",
    slides: [
      { icon: "📅", text: "Days 1–10: cover all science topics — 2 chapters/day, no skipping" },
      { icon: "🧩", text: "Days 11–20: logical reasoning daily + Achievers-style questions" },
      { icon: "📝", text: "Days 21–28: two full timed mock papers — review mistakes by topic" },
      { icon: "🛌", text: "Days 29–30: light revision only. Sleep and confidence matter now." },
    ],
  },
  {
    id: "blog-15",
    slug: "spell-bee-class-4",
    title: "Spell Bee Prep for Class 4",
    hook: "Spell Bee isn't about memorising a dictionary. Here's what actually works.",
    tag: "Spell Bee · Class 4",
    color: "#f59e0b",
    audience: "parents",
    slides: [
      { icon: "🔤", text: "Focus on word patterns — silent letters, double letters, -tion/-cion endings" },
      { icon: "📚", text: "Learn the meaning with the spelling — it locks the word in memory better" },
      { icon: "🗣️", text: "Say it, spell it, write it — the 3-step method works for every word" },
      { icon: "🎯", text: "High-frequency Class 4 categories: animals, food, weather, body parts" },
    ],
  },
  {
    id: "blog-16",
    slug: "spell-bee-class-5",
    title: "Spell Bee Word List for Class 5",
    hook: "Class 5 Spell Bee has patterns. Master the patterns, master the list.",
    tag: "Spell Bee · Class 5",
    color: "#f59e0b",
    audience: "students",
    slides: [
      { icon: "📝", text: "Silent letters trap most students — knife, gnome, wrist, psychology" },
      { icon: "🔁", text: "Homophones: their/there/they're · principal/principle · affect/effect" },
      { icon: "🧩", text: "Suffix rules: -ible vs -able · -ise vs -ize · -er vs -or" },
      { icon: "💡", text: "Read widely — context recognition beats rote memorisation every time" },
    ],
  },
  {
    id: "blog-17",
    slug: "spell-bee-preparation",
    title: "Spell Bee: Complete Guide Class 1–12",
    hook: "From Class 1 to Class 12 — here's how Spell Bee prep changes each year.",
    tag: "Spell Bee",
    color: "#f59e0b",
    audience: "parents",
    slides: [
      { icon: "🔡", text: "Class 1–3: phonics and common 3–4 letter words, CVC patterns" },
      { icon: "📖", text: "Class 4–6: word families, silent letters, compound words, homophones" },
      { icon: "🎓", text: "Class 7–10: etymology, prefixes/suffixes, technical vocabulary" },
      { icon: "🏆", text: "Class 11–12: advanced vocabulary, idioms, literary and academic words" },
    ],
  },
  {
    id: "blog-18",
    slug: "best-olympiad-app",
    title: "Best Olympiad App in India 2025–26",
    hook: "What should you actually look for in an Olympiad prep app?",
    tag: "AI & Learning",
    color: "#0EA5A4",
    audience: "parents",
    slides: [
      { icon: "🤖", text: "AI-generated questions > static question banks — no repeats, always fresh" },
      { icon: "🧠", text: "Explanation quality matters more than question count — look for step-by-step" },
      { icon: "📊", text: "Progress tracking and weak topic detection = the features that improve scores" },
      { icon: "🆓", text: "Always try free first — any serious app offers free practice before payment" },
    ],
  },
  {
    id: "blog-19",
    slug: "olympiad-preparation-class-6-10",
    title: "Olympiad Prep: Classes 6–10 Subject Guide",
    hook: "Classes 6–10 are when Olympiad preparation gets strategic.",
    tag: "Guides · Class 6–10",
    color: "#8b5cf6",
    audience: "parents",
    slides: [
      { icon: "📐", text: "Class 6: integers & algebra enter the picture — biggest syllabus jump" },
      { icon: "🔬", text: "Class 7–8: science splits into disciplines, maths adds identities" },
      { icon: "🎯", text: "Class 9–10: board overlap is highest — Olympiad prep = board prep" },
      { icon: "⚡", text: "Achievers section becomes more important every year — start early" },
    ],
  },
  {
    id: "blog-20",
    slug: "olympiad-preparation-class-1-5",
    title: "Olympiad Prep: Classes 1–5 Beginner Guide",
    hook: "Starting Olympiads in Class 1? Here's what parents need to know.",
    tag: "Guides · Class 1–5",
    color: "#8b5cf6",
    audience: "parents",
    slides: [
      { icon: "🌱", text: "Classes 1–2: single level, participation focus, build the habit" },
      { icon: "📈", text: "Class 3: Level 2 qualification begins — Achievers section starts mattering" },
      { icon: "⏱️", text: "10–15 min/day is enough — consistency beats intensity at this age" },
      { icon: "😊", text: "Keep it positive — a child who enjoys maths at 6 is worth more than a medal" },
    ],
  },
  {
    id: "blog-21",
    slug: "imo-nso-ieo-explained",
    title: "IMO, NSO & IEO Explained for Parents",
    hook: "IMO, NSO, IEO — what are they, who runs them, and which should your child take?",
    tag: "Guides",
    color: "#8b5cf6",
    audience: "parents",
    slides: [
      { icon: "➕", text: "IMO: International Maths Olympiad by SOF · Class 1–12 · most popular" },
      { icon: "🔬", text: "NSO: National Science Olympiad by SOF · physics, chemistry, biology" },
      { icon: "📖", text: "IEO: International English Olympiad · grammar, vocabulary, comprehension" },
      { icon: "📋", text: "All three: school-based registration, no travel, 60-minute paper" },
    ],
  },
  {
    id: "blog-22",
    slug: "how-to-prepare-for-imo",
    title: "How to Prepare for IMO: Step-by-Step",
    hook: "The IMO gold medal is earned in the months before exam day. Here's how.",
    tag: "Maths",
    color: "#2563EB",
    audience: "students",
    slides: [
      { icon: "1️⃣", text: "Step 1: Download the syllabus — know exactly what's tested" },
      { icon: "2️⃣", text: "Step 2: Identify weak topics — spend 60% of prep time here" },
      { icon: "3️⃣", text: "Step 3: Achievers section last — it's the same topics, harder framing" },
      { icon: "4️⃣", text: "Step 4: One timed full mock, two weeks before — review every wrong answer" },
    ],
  },
  {
    id: "blog-23",
    slug: "olympiad-preparation-tips",
    title: "12 Olympiad Prep Tips You Can Start Today",
    hook: "12 things top Olympiad students do that most students skip.",
    tag: "Tips",
    color: "#ef4444",
    audience: "students",
    slides: [
      { icon: "📝", text: "Keep a mistake log — review it the week before the exam" },
      { icon: "⏱️", text: "Practise under a timer from week one — not just the week before" },
      { icon: "🧩", text: "Don't skip logical reasoning — it's often the easiest marks on the paper" },
      { icon: "🔄", text: "Revise a topic 3 days later, then 7 days later — spaced repetition works" },
    ],
  },
  {
    id: "blog-24",
    slug: "ai-olympiad-preparation",
    title: "How AI Is Changing Olympiad Prep",
    hook: "AI doesn't just generate questions — it finds what your child doesn't know.",
    tag: "AI & Learning",
    color: "#0EA5A4",
    audience: "parents",
    slides: [
      { icon: "🤖", text: "AI generates fresh questions every session — no repetition, no memorising patterns" },
      { icon: "🧠", text: "Instant AI explanations: not just ✓ or ✗ but why, step by step" },
      { icon: "📊", text: "Weak topic detection: AI spots which chapters need more time" },
      { icon: "⏰", text: "Available 24/7 — doubt at 10 PM? AI tutor answers immediately" },
    ],
  },
  {
    id: "blog-25",
    slug: "how-to-prepare-for-nso",
    title: "How to Prepare for NSO: Complete Guide",
    hook: "NSO rewards application over memory. Here's how to prep for it.",
    tag: "Science",
    color: "#10b981",
    audience: "students",
    slides: [
      { icon: "🔬", text: "NSO = CBSE science + logical reasoning + Achievers application questions" },
      { icon: "📖", text: "Read to understand mechanisms — not just definitions" },
      { icon: "🧩", text: "Logical reasoning is 15 questions — most students under-prepare it" },
      { icon: "📝", text: "One timed mock paper per subject, 2 weeks out — then just review mistakes" },
    ],
  },
  {
    id: "blog-26",
    slug: "how-to-prepare-for-ieo",
    title: "How to Prepare for IEO",
    hook: "IEO isn't just grammar. Vocabulary and reading inference decide your rank.",
    tag: "English",
    color: "#0EA5A4",
    audience: "students",
    slides: [
      { icon: "📖", text: "Reading comprehension = 30–40% of marks · inference questions are hardest" },
      { icon: "✍️", text: "Grammar focus: tenses, active/passive voice, conditionals — all are tested" },
      { icon: "🔤", text: "Vocabulary: idioms, phrasal verbs, collocations — read daily to build these" },
      { icon: "💡", text: "Low prep overhead — 3–4 weeks is enough if English is already a strength" },
    ],
  },
  {
    id: "blog-27",
    slug: "benefits-of-olympiad-exams",
    title: "8 Real Benefits of Olympiad Exams",
    hook: "Beyond medals — here's what Olympiads actually do for your child.",
    tag: "Guides",
    color: "#8b5cf6",
    audience: "parents",
    slides: [
      { icon: "🧠", text: "Builds problem-solving depth that board exams don't test" },
      { icon: "📈", text: "Students who do Olympiads consistently outperform peers in board exams" },
      { icon: "🎓", text: "National rank strengthens applications for IB, scholarships, premier schools" },
      { icon: "💪", text: "Builds exam confidence — a child who handles Olympiad pressure handles boards easily" },
    ],
  },
  {
    id: "blog-28",
    slug: "how-to-improve-logical-reasoning",
    title: "How to Improve Logical Reasoning for Olympiads",
    hook: "Logical reasoning is the most learnable section — and the most skipped.",
    tag: "Tips",
    color: "#ef4444",
    audience: "students",
    slides: [
      { icon: "🔢", text: "Number series: find the rule first, then apply — don't guess" },
      { icon: "🗺️", text: "Direction problems: always draw a small diagram — it removes errors" },
      { icon: "🔡", text: "Coding-decoding: write the alphabet with numbers (A=1, B=2...) on rough paper" },
      { icon: "📅", text: "One reasoning type per day, 10 minutes — you'll see improvement in 2 weeks" },
    ],
  },
];
