// Seed bank of Olympiad-style questions. The bot picks 2 per day
// (one for the morning slot, one for the evening slot) using a deterministic
// rotation keyed on the IST date — so you can predict in advance what will go
// out and override by dropping captions.json or pre-baked images.
//
// Format mirrors marketing/quiz-data.js:
//   { id, subject, grade, question, options:[4], answer:0-3, explanation }
//
// Drop more entries here over time. The rotation just `idx % length`s so
// adding more questions = more variety automatically.

module.exports = [
  // ── Maths ────────────────────────────────────────────────────────
  { id: "m-001", subject: "Mathematics", grade: 5,
    question: "What is the smallest 3-digit number divisible by both 4 and 5?",
    options: ["100", "120", "105", "140"], answer: 0,
    explanation: "Numbers divisible by 4 and 5 are divisible by 20. 100 is the smallest 3-digit multiple of 20." },
  { id: "m-002", subject: "Mathematics", grade: 6,
    question: "If 3ˣ = 81, what is the value of x?",
    options: ["3", "5", "4", "6"], answer: 2,
    explanation: "3⁴ = 3 × 3 × 3 × 3 = 81, so x = 4." },
  { id: "m-003", subject: "Mathematics", grade: 7,
    question: "The sum of three consecutive integers is 96. What is the largest?",
    options: ["31", "32", "33", "34"], answer: 2,
    explanation: "Let them be n−1, n, n+1. Sum = 3n = 96 → n = 32. Largest is 33." },
  { id: "m-004", subject: "Mathematics", grade: 6,
    question: "Which fraction is greatest: 2/3, 3/4, 5/8, 7/12?",
    options: ["2/3", "3/4", "5/8", "7/12"], answer: 1,
    explanation: "Common denominator 24 → 16/24, 18/24, 15/24, 14/24. Largest is 18/24 = 3/4." },
  { id: "m-005", subject: "Mathematics", grade: 8,
    question: "What is the value of (√144) + (√169)?",
    options: ["23", "25", "26", "27"], answer: 1,
    explanation: "√144 = 12 and √169 = 13. 12 + 13 = 25." },
  { id: "m-006", subject: "Mathematics", grade: 7,
    question: "If the perimeter of a square is 64 cm, what is its area?",
    options: ["256 cm²", "128 cm²", "64 cm²", "192 cm²"], answer: 0,
    explanation: "Side = 64/4 = 16. Area = 16 × 16 = 256 cm²." },
  { id: "m-007", subject: "Mathematics", grade: 5,
    question: "What comes next: 2, 6, 12, 20, 30, …?",
    options: ["40", "42", "36", "44"], answer: 1,
    explanation: "Differences: 4, 6, 8, 10, 12. Next term = 30 + 12 = 42." },
  { id: "m-008", subject: "Mathematics", grade: 9,
    question: "If a = 2 and b = 3, what is a³ + b²?",
    options: ["17", "13", "19", "15"], answer: 0,
    explanation: "a³ = 8, b² = 9. 8 + 9 = 17." },
  { id: "m-009", subject: "Mathematics", grade: 6,
    question: "What is 15% of 240?",
    options: ["36", "30", "32", "40"], answer: 0,
    explanation: "15% of 240 = (15/100) × 240 = 36." },
  { id: "m-010", subject: "Mathematics", grade: 8,
    question: "The HCF of 24 and 36 is:",
    options: ["6", "8", "12", "18"], answer: 2,
    explanation: "Factors: 24 = 2³×3, 36 = 2²×3². HCF = 2²×3 = 12." },

  // ── English ──────────────────────────────────────────────────────
  { id: "e-001", subject: "English", grade: 6,
    question: "Choose the correctly spelled word:",
    options: ["Accomodate", "Accommodate", "Acommodate", "Acommadate"], answer: 1,
    explanation: "“Accommodate” has double c and double m — a common spelling trap." },
  { id: "e-002", subject: "English", grade: 7,
    question: "Pick the antonym of TRANSPARENT:",
    options: ["Clear", "Visible", "Opaque", "Glassy"], answer: 2,
    explanation: "Opaque means not able to be seen through — the opposite of transparent." },
  { id: "e-003", subject: "English", grade: 5,
    question: "Identify the noun: “The puppy ran across the garden.”",
    options: ["ran", "across", "puppy", "the"], answer: 2,
    explanation: "“Puppy” names a thing (a young dog), so it is a noun." },
  { id: "e-004", subject: "English", grade: 8,
    question: "Choose the synonym of BENEVOLENT:",
    options: ["Cruel", "Kind", "Greedy", "Quiet"], answer: 1,
    explanation: "Benevolent means well-meaning and kindly — closest match is “kind”." },
  { id: "e-005", subject: "English", grade: 6,
    question: "Fill the blank: She is _____ honest girl.",
    options: ["a", "an", "the", "no article"], answer: 1,
    explanation: "“Honest” starts with a silent ‘h’ — the spoken sound is a vowel, so use “an”." },
  { id: "e-006", subject: "English", grade: 7,
    question: "Pick the correctly punctuated sentence:",
    options: [
      "Where are you going.",
      "Where are you going!",
      "Where are you going?",
      "Where, are you going."
    ], answer: 2,
    explanation: "It’s a question, so it ends with a question mark." },
  { id: "e-007", subject: "English", grade: 9,
    question: "Choose the meaning of the idiom: “Once in a blue moon”.",
    options: ["Very often", "Very rarely", "At night", "Suddenly"], answer: 1,
    explanation: "“Once in a blue moon” means something that happens very rarely." },
  { id: "e-008", subject: "English", grade: 6,
    question: "Pick the verb in: “The children sang beautifully.”",
    options: ["children", "sang", "beautifully", "the"], answer: 1,
    explanation: "“Sang” is the action — it’s the verb." },
  { id: "e-009", subject: "English", grade: 8,
    question: "Choose the correct word: He is the _____ player in the team.",
    options: ["good", "better", "best", "well"], answer: 2,
    explanation: "Comparing more than two, use the superlative “best”." },
  { id: "e-010", subject: "English", grade: 7,
    question: "Which word is a preposition?",
    options: ["Quickly", "Under", "Bright", "Run"], answer: 1,
    explanation: "“Under” shows position — it’s a preposition." },
];
